# Generated by Django 3.2 on 2022-05-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220525_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='stream_platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='movies.streamplatform'),
            preserve_default=False,
        ),
    ]
