# Generated by Django 3.1.6 on 2022-06-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220612_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='number_of_reviews',
            new_name='number_of_ratings',
        ),
    ]
